categories = Category.create([{category_name: "Board Games"},
                              {category_name: "Books"},
                              {category_name: "Camping Gears"},
                              {category_name: "Cars & Vehicles"},
                              {category_name: "Furniture"},
                              {category_name: "Jewelry	&	Clothes"},
                              {category_name: "Kids Costums"},
                              {category_name: "Office Supplies"},
                              {category_name: "Sports Equipments"},
                              {category_name: "Tools"},
                              {category_name: "Toys"},
                              {category_name: "Video Games"}])
